### PR TITLE
Page/donate changes

### PR DESCRIPTION
**Pull request by ShepleySound**
# Changes
- Added a `children` slot in the Hero Banner component. It only takes a single React element, and it _only_ renders if the `imgsrc` prop is not given.
- Added a bottom gutter to elements that render as `<p>` tags in the Hero Banner subheading.
- Tweaked attributes of the donorbox iframe, as well as the surrounding container.
- Render a NextJS `<Script/>` element on the /donate page that handles fitting the iframe to its parent container, taken from the donorbox embed instructions.

### CODE REVIEW

**Comment by e-papanicolas** [comment]
The make a donation by check FAQ on this page shows: Donorbox has the capability for direct ACH payments, but you are still welcome to mail a check. Please make the check out to Clearviction and mail it to: **/formbat** Seamus Brugh 802 5th Ave N, unit 213 Seattle, WA 98109

**Comment by ShepleySound** [comment]
> @ShepleySound The make a donation by check FAQ on this page shows: Donorbox has the capability for direct ACH payments, but you are still welcome to mail a check. Please make the check out to Clearviction and mail it to: **/formbat** Seamus Brugh 802 5th Ave N, unit 213 Seattle, WA 98109

Thank you for the catch! I've corrected this, as well as some other color/format issues present overall.

**Comment by e-papanicolas** [comment]
> > @ShepleySound The make a donation by check FAQ on this page shows: Donorbox has the capability for direct ACH payments, but you are still welcome to mail a check. Please make the check out to Clearviction and mail it to: **/formbat** Seamus Brugh 802 5th Ave N, unit 213 Seattle, WA 98109
> 
> Thank you for the catch! I've corrected this, as well as some other color/format issues present overall.

Great! I had made a note to ask why we were putting Seamus' (what looks like) home address out there. Removing it seems like the right fix.

**Comment by mhyneman8** [comment]
@ShepleySound The visit our donorbox page should open to a new tab, not take the user away from our site.

**Pull request merged**
