### PR TITLE
Add images to calculator pages

### PR DESCRIPTION
**Pull request by e-papanicolas**
**This pull request does the following:**

1. Adds the image field to the sanity queries page for the calculator. This corresponds to [PR #3 in clearviction-sanity](https://github.com/openseattle/clearviction-sanity/pull/3) which adds all of the corresponding type information so that it can be filled in on Sanity Studio.

_Still to be done:_

- Add the image field in the UI components
- Attach all of the pictures to their corresponding pages in Sanity Studio

### CODE REVIEW

**Review by ShepleySound — COMMENTED** [review]
Great! Thank you for the incremental change. Let's keep this PR open for now so that we can merge the full feature in when it's ready.

**Comment by e-papanicolas** [comment]
@ShepleySound ok, I wasn't sure if this needed to be merged so that the sanity queries groq match up with the config schema.

**Comment by e-papanicolas** [comment]
@nurselaine Let's get rid of all of the console.log statements before this gets merged please! Also, we should not be pushing the .env file up, it should be removed and .env added to the .gitignore.

**Comment by nurselaine** [comment]
Hey Eleni - thanks for the feedback and good catch on .env. I'm still working on adding the images styles as well as refactoring the code. I'll make sure to request a review once the task is all done!

**Comment by nurselaine** [comment]
Images have been added to page. One issue adding these images was the placement on the page due to how React's portable text component is currently set-up. At the moment, Sanity.io content is set-up so the title and page description are imported as one object that cannot be separated, so the image cannot be styled to match the figma designs for certain pages.

**Comment by e-papanicolas** [comment]
That .env file has been haunting me on all the new branches I've been working in 😵‍💫

**Comment by e-papanicolas** [comment]
@nurselaine I get a glitch on every page with an image, it has the previous image for a visible moment, before updating to the new image.

**Comment by nurselaine** [comment]
@e-papanicolas I hope this helps. I just reverted it but let me know if you're still have issues on your end. and oh my god I had no idea my .env got pushed up!

**Comment by e-papanicolas** [comment]
Hmm it is still happening, I can take a closer look tomorrow.

**Comment by nurselaine** [comment]
Added in a prop to next/image component that should properly load images. Hope this helps with the image glitch on every page!

**Comment by mhyneman8** [comment]
Not to just jump in and sound like a broken record, but there is still a noticeable lag on the image loading. We don't want to distract from the calculator. Currently, it would be better to keep no images than to have images that don't load with the 'page'.

**Comment by F-Rivers** [comment]
please see slack: cop_dev

**Pull request closed without merging**
