### PR TITLE
Page/get involved

### PR DESCRIPTION
**Pull request by nurselaine**
Rebuilt Get Involved page. - https://airtable.com/appfJZShN8K4tcWHU/tblXQZfKPAJIjV4cL/viwvHcIFhPuIIE4uC/recvbS31Pt80uxjT5?blocks=hide

Need to convert page to tsx.
Looking for feedback potentially on spacing. There's some extra white space in the partner section and crowding in the hero banner.

Potential Opportunity for future changes:
- Updating buttons to yellow color on hover 
- Create a button component to standardize all buttons on website 
- Fix spacing issue with hero banner volunteer card 
- Adjust image sizes in hero banner cards

### CODE REVIEW

**Comment by e-papanicolas** [comment]
This is a very small fix, but the file name volunter.tsx is missing an e.

**Review by e-papanicolas — COMMENTED** [review]
I think that the content/get-involved file was accidentally deleted, so I put it back, as well as fixed a few file name imports. Other than that, everything seems to have been migrated over correctly!

**Review by ShepleySound — CHANGES_REQUESTED** [review]
Thank you for all of the work! I'd like to request a few changes, just so we can continue moving towards a more consistent code style -

1. Check out this branch that I've made. It takes the hero banner and breaks the cards out of it, and uses MUI's `Card` component instead of creating a new component from scratch. It also replaces the "marketing" image with the "horn" image, which was given to us by design as a version with 0 padding. - https://github.com/openseattle/clearviction-next/blob/REVISION/get-involved/pages/get-involved.jsx

2. Any file in the `pages` folder gets turned into a page, so your `partner.tsx` component is actually creating an entirely new page at localhost:3000/partner. There's not too much of a need to break pages into their own components, but if you feel they're getting too long and you would like to separate sections for code readability, I'd recommend placing the new components in the same file without exporting them.

3. We can get rid of the `useTheme()` hook here, since it's just being used to invoke `theme.spacing(x)`. When inside the `sx` prop, `mt: 8` is equivalent to `mt: theme.spacing(8)`. It automatically uses the current theme in context. Also, if you're setting mt & mb, then the `my` prop can be used as shorthand for both!

**Review by ShepleySound — APPROVED** [review]
Looks great @nurselaine! Thank you again for building this out!

**Pull request merged**
